name: Docker Image CI

on:
  push:
    branches: [ "codespace-special-umbrella-7v6qvg55jxvghw55v" ]
  pull_request:
    branches: [ "codespace-special-umbrella-7v6qvg55jxvghw55v" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
